-- ================================================================
-- PetroFlow — MULTI-COMPANY ISOLATION & STABILIZATION SCRIPT
-- ================================================================
-- PURPOSE: 
-- 1. Implements Multi-Tenancy (Data Isolation by Company).
-- 2. Adds Invitation System for staff members.
-- 3. Standardizes company_id across all tables.
-- ================================================================

-- STEP 1: CREATE CORE TENANCY TABLES
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.companies (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL DEFAULT 'My Petrol Pump',
    owner_id UUID REFERENCES auth.users(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.staff_invites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    company_id UUID REFERENCES public.companies(id) ON DELETE CASCADE,
    role TEXT NOT NULL DEFAULT 'employee',
    status TEXT DEFAULT 'pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- STEP 2: ALTER TABLES TO ADD company_id
-- ----------------------------------------------------------------
DO $$ 
DECLARE 
    r RECORD;
BEGIN 
    -- 1. Add company_id to user_profiles if missing
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'user_profiles' AND column_name = 'company_id') THEN
        ALTER TABLE public.user_profiles ADD COLUMN company_id UUID REFERENCES public.companies(id);
    END IF;

    -- 2. Loop through all critical tables and add company_id
    FOR r IN (
        SELECT table_name 
        FROM information_schema.tables 
        WHERE table_schema = 'public' 
        AND table_name IN (
            'customers', 'transactions', 'expense_categories', 'cash_advances', 
            'company_transactions', 'company_repayments', 'mobil_sales', 'mobil_stock',
            'mobil_transactions', 'rent_payments', 'settings', 'shops', 'stock_entries',
            'stock_purchases', 'tanks', 'expense_types', 'member_card_usage', 'mobil_arrivals',
            'mobil_product_prices', 'mobil_products', 'price_history', 'banks', 'cash_deposits'
        )
    ) LOOP
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = r.table_name AND column_name = 'company_id') THEN
            EXECUTE format('ALTER TABLE public.%I ADD COLUMN company_id UUID REFERENCES public.companies(id)', r.table_name);
        END IF;
    END LOOP;
END $$;

-- STEP 3: REBUILD IDENTITY HELPERS
-- ----------------------------------------------------------------
DO $$ 
DECLARE r RECORD;
BEGIN 
    FOR r IN (
        SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' 
        AND table_name IN ('customers', 'transactions', 'banks', 'tanks', 'expense_categories')
    ) LOOP
        BEGIN
            EXECUTE format('ALTER TABLE public.%I ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY', r.table_name);
        EXCEPTION WHEN OTHERS THEN NULL;
        END;
    END LOOP;
END $$;

-- STEP 4: ENHANCED AUTH TRIGGER (Multi-Tenant)
-- ----------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
DECLARE
    target_company_id UUID;
    target_role TEXT := 'employee';
    inv_id BIGINT;
BEGIN
    -- 1. Check if user is invited
    SELECT id, company_id, role INTO inv_id, target_company_id, target_role
    FROM public.staff_invites WHERE email = NEW.email;

    -- 2. Create profile
    INSERT INTO public.user_profiles (user_id, email, role, status, company_id)
    VALUES (NEW.id, NEW.email, target_role, 'pending', target_company_id)
    ON CONFLICT (user_id) DO UPDATE SET email = EXCLUDED.email;

    -- 3. If Admin and NO company yet, create one
    IF target_role = 'admin' AND target_company_id IS NULL THEN
        -- We will assign the company later or use a default
        INSERT INTO public.companies (name, owner_id)
        VALUES ('My Petrol Pump', NEW.id)
        RETURNING id INTO target_company_id;
        
        UPDATE public.user_profiles SET company_id = target_company_id WHERE user_id = NEW.id;
    END IF;

    -- 4. Mark invite as accepted
    IF inv_id IS NOT NULL THEN
        DELETE FROM public.staff_invites WHERE id = inv_id;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Re-attach trigger
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- STEP 5: RLS POLICIES (Data Isolation)
-- ----------------------------------------------------------------
ALTER TABLE public.companies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.staff_invites ENABLE ROW LEVEL SECURITY;

-- Helper to check if user belongs to a company (NON-RECURSIVE)
CREATE OR REPLACE FUNCTION public.get_my_company()
RETURNS UUID LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  RETURN (SELECT company_id FROM public.user_profiles WHERE user_id = auth.uid());
END;
$$;

-- Helper to check if user is super_admin (NON-RECURSIVE)
CREATE OR REPLACE FUNCTION public.check_is_super_admin()
RETURNS BOOLEAN LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  RETURN EXISTS (SELECT 1 FROM public.user_profiles WHERE user_id = auth.uid() AND role = 'super_admin');
END;
$$;

-- Global Isolation Policy (Standard for almost all tables)
CREATE OR REPLACE FUNCTION public._apply_isolation_v1(tbl TEXT)
RETURNS VOID LANGUAGE plpgsql AS $$
BEGIN
  -- 1. Enable RLS
  EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', tbl);
  
  -- 2. Drop existing
  EXECUTE format('DROP POLICY IF EXISTS isolation_policy ON public.%I', tbl);
  
  -- 3. Create Isolation Policy (Bypasses recursion via Security Definer functions)
  EXECUTE format('CREATE POLICY isolation_policy ON public.%I FOR ALL TO authenticated USING (
    public.check_is_super_admin()
    OR company_id = public.get_my_company()
  )', tbl);

  -- 4. AUTO-ASSIGN company_id on INSERT (Smoothest flow)
  BEGIN
    EXECUTE format('ALTER TABLE public.%I ALTER COLUMN company_id SET DEFAULT public.get_my_company()', tbl);
  EXCEPTION WHEN OTHERS THEN NULL;
  END;
END $$;

-- Apply to all data tables
SELECT public._apply_isolation_v1('user_profiles');
SELECT public._apply_isolation_v1('customers');
SELECT public._apply_isolation_v1('transactions');
SELECT public._apply_isolation_v1('tanks');
SELECT public._apply_isolation_v1('banks');

-- Special Policy for Companies (Isolated by ID/Owner)
ALTER TABLE public.companies ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS isolation_policy ON public.companies;
CREATE POLICY isolation_policy ON public.companies FOR ALL TO authenticated USING (
    id = public.get_my_company() 
    OR owner_id = auth.uid() 
    OR EXISTS (SELECT 1 FROM public.user_profiles WHERE user_id = auth.uid() AND role = 'super_admin')
);

-- Special Policy for Invites (Isolated by company_id OR email)
ALTER TABLE public.staff_invites ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS isolation_policy ON public.staff_invites;
CREATE POLICY isolation_policy ON public.staff_invites FOR ALL TO authenticated USING (
    company_id = public.get_my_company()
    OR email = (SELECT email FROM auth.users WHERE id = auth.uid())
    OR EXISTS (SELECT 1 FROM public.user_profiles WHERE user_id = auth.uid() AND role = 'super_admin')
);

-- STEP 6: MIGRATION FOR EXISTING USERS
-- ----------------------------------------------------------------
DO $$ 
DECLARE r RECORD;
DECLARE new_cid UUID;
BEGIN 
    -- 1. Create companies for Admins who don't have one
    FOR r IN (SELECT user_id FROM public.user_profiles WHERE role = 'admin' AND company_id IS NULL) LOOP
        INSERT INTO public.companies (name, owner_id) VALUES ('My Petrol Pump', r.user_id) 
        RETURNING id INTO new_cid;
        UPDATE public.user_profiles SET company_id = new_cid WHERE user_id = r.user_id;
    END LOOP;

    -- 2. (Optional) Assign employees to the FIRST admin if they have no company
    -- For now, we leave them NULL so they can be manually assigned or use an invite.
END $$;

-- STEP 7: INITIAL DATA & MISSING SCHEMA PATCHES
-- ----------------------------------------------------------------
DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='customers' AND column_name='balance') THEN
    ALTER TABLE public.customers ADD COLUMN balance NUMERIC(14,2) DEFAULT 0;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='customers' AND column_name='is_company') THEN
    ALTER TABLE public.customers ADD COLUMN is_company BOOLEAN DEFAULT false;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='customers' AND column_name='company_name') THEN
    ALTER TABLE public.customers ADD COLUMN company_name TEXT;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='customers' AND column_name='credit_limit') THEN
    ALTER TABLE public.customers ADD COLUMN credit_limit NUMERIC(14,2) DEFAULT 0;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='tanks' AND column_name='current_stock') THEN
    ALTER TABLE public.tanks ADD COLUMN current_stock NUMERIC(14,2) DEFAULT 0;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='tanks' AND column_name='capacity') THEN
    ALTER TABLE public.tanks ADD COLUMN capacity NUMERIC(14,2) DEFAULT 25000;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='transactions' AND column_name='amount') THEN
    ALTER TABLE public.transactions ADD COLUMN amount NUMERIC(14,2) DEFAULT 0;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='transactions' AND column_name='expense_type') THEN
    ALTER TABLE public.transactions ADD COLUMN expense_type TEXT;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='transactions' AND column_name='expense_account') THEN
    ALTER TABLE public.transactions ADD COLUMN expense_account TEXT;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='transactions' AND column_name='notes') THEN
    ALTER TABLE public.transactions ADD COLUMN notes TEXT;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='transactions' AND column_name='description') THEN
    ALTER TABLE public.transactions ADD COLUMN description TEXT;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='transactions' AND column_name='transaction_type') THEN
    ALTER TABLE public.transactions ADD COLUMN transaction_type TEXT DEFAULT 'CashSale';
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='transactions' AND column_name='fuel_type') THEN
    ALTER TABLE public.transactions ADD COLUMN fuel_type TEXT;
  END IF;

  -- ── Daily Readings required columns ─────────────────────────
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='transactions' AND column_name='liters') THEN
    ALTER TABLE public.transactions ADD COLUMN liters NUMERIC(14,3);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='transactions' AND column_name='unit_price') THEN
    ALTER TABLE public.transactions ADD COLUMN unit_price NUMERIC(14,2);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='transactions' AND column_name='charges') THEN
    ALTER TABLE public.transactions ADD COLUMN charges NUMERIC(14,2) DEFAULT 0;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='transactions' AND column_name='entry_method') THEN
    ALTER TABLE public.transactions ADD COLUMN entry_method TEXT;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='transactions' AND column_name='payment_method') THEN
    ALTER TABLE public.transactions ADD COLUMN payment_method TEXT;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='transactions' AND column_name='cash_advance_id') THEN
    ALTER TABLE public.transactions ADD COLUMN cash_advance_id BIGINT;
  END IF;

END $$;

INSERT INTO public.expense_categories (name, icon) VALUES 
('Petrol Stock', '⛽'), ('Diesel Stock', '⛽'), ('Electricity Bill', '⚡'), ('Staff Salary', '👷')
ON CONFLICT (name) DO NOTHING;

DO $$ 
BEGIN
    RAISE NOTICE 'Multi-Company Isolation Applied Successfully!';
END $$;

-- STEP 8: RE-CREATE OR UPDATE REPORTING VIEWS
-- ----------------------------------------------------------------
-- Stock balance by fuel type
CREATE OR REPLACE VIEW public.v_stock_by_fuel AS
SELECT fuel_type, COALESCE(SUM(current_stock),0) AS total_stock, COALESCE(SUM(capacity),0) AS total_capacity
FROM public.tanks
GROUP BY fuel_type;

-- Company account summary
CREATE OR REPLACE VIEW public.v_company_account_summary AS
SELECT
  c.id, c.name, c.sr_no, c.credit_limit, c.balance,
  COALESCE(SUM(CASE WHEN ct.direction='out' AND ct.txn_type='stock_purchase' THEN ct.amount ELSE 0 END),0) AS total_stock_purchased,
  COALESCE(SUM(CASE WHEN ct.direction='out' AND ct.txn_type='member_usage' THEN ct.amount ELSE 0 END),0) AS total_member_usage,
  COALESCE(SUM(CASE WHEN ct.direction='out' THEN ct.charges ELSE 0 END),0) AS total_charges,
  COALESCE(SUM(CASE WHEN ct.direction='in'  THEN ct.amount ELSE 0 END),0) AS total_repaid
FROM public.customers c
LEFT JOIN public.company_transactions ct ON ct.company_id = c.id
WHERE c.is_company = TRUE
GROUP BY c.id, c.name, c.sr_no, c.credit_limit, c.balance;

-- Expense ledger
CREATE OR REPLACE VIEW public.v_expense_ledger AS
SELECT
  t.id, t.created_at AS expense_date, t.amount, t.description, t.notes,
  t.transaction_type, t.fuel_type, t.user_id,
  t.expense_type AS category, t.expense_account AS paid_from,
  c.name AS account_name, c.sr_no AS account_no
FROM public.transactions t
LEFT JOIN public.customers c ON c.id = t.customer_id
WHERE t.transaction_type = 'Expense';

-- Member usage summary
CREATE OR REPLACE VIEW public.v_member_usage_summary AS
SELECT
  m.id AS member_id, m.name AS member_name, m.sr_no AS member_no,
  co.name AS company_name,
  MAX(mcu.fuel_type) AS fuel_type,
  COUNT(mcu.id) AS usage_count,
  COALESCE(SUM(mcu.liters),0) AS total_liters,
  COALESCE(SUM(mcu.liters * mcu.unit_price),0) AS stock_value,
  COALESCE(SUM(mcu.atm_charges + mcu.misc_charges),0) AS total_charges,
  COALESCE(SUM(mcu.liters * mcu.unit_price) + SUM(mcu.atm_charges + mcu.misc_charges), 0) AS grand_total
FROM public.customers m
JOIN public.member_card_usage mcu ON mcu.member_id = m.id
JOIN public.customers co ON co.id = mcu.company_id
GROUP BY m.id, m.name, m.sr_no, co.name;
