-- ================================================================
-- PetroFlow — MASTER DATABASE REPAIR & STABILIZATION SCRIPT
-- ================================================================
-- PURPOSE: 
-- 1. Corrects tables that were created without auto-increment IDs.
-- 2. Standardizes ID columns to BIGINT IDENTITY.
-- 3. Fixes Foreign Key relationships.
-- 4. Rebuilds the Auth Trigger and RLS policies.
-- ================================================================

-- STEP 1: SELF-HEALING IDENTITY FIX (The "Power Block")
-- This block scans ALL public tables and adds "Auto-Increment" to any missing IDs.
-- ----------------------------------------------------------------
DO $$ 
DECLARE 
    r RECORD;
BEGIN 
    -- 1. Fix user_profiles first (Compatibility with Auth)
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'user_profiles' AND column_name = 'id' AND data_type = 'uuid') THEN
       -- If it's a UUID, we keep it as is, but ensure it's the primary key
       NULL;
    ELSE
       -- If it is a BIGINT, ensure it has a sequence or identity
       BEGIN
          ALTER TABLE public.user_profiles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
       EXCEPTION WHEN OTHERS THEN 
          RAISE NOTICE 'user_profiles.id already has identity/sequence';
       END;
    END IF;

    -- 2. Loop through a list of critical tables and force Identity/BigInt
    FOR r IN (
        SELECT table_name 
        FROM information_schema.tables 
        WHERE table_schema = 'public' 
        AND table_name IN (
            'customers', 'transactions', 'expense_categories', 'cash_advances', 
            'company_transactions', 'company_repayments', 'mobil_sales', 'mobil_stock',
            'mobil_transactions', 'rent_payments', 'settings', 'shops', 'stock_entries',
            'stock_purchases', 'tanks', 'expense_types', 'member_card_usage', 'mobil_arrivals',
            'mobil_product_prices', 'mobil_products', 'price_history', 'banks', 'cash_deposits'
        )
    ) LOOP
        -- a. Ensure column is BIGINT
        BEGIN
            EXECUTE format('ALTER TABLE public.%I ALTER COLUMN id SET DATA TYPE BIGINT', r.table_name);
        EXCEPTION WHEN OTHERS THEN
            RAISE NOTICE 'Skipped type cast for % (maybe already bigint or incompatible)', r.table_name;
        END;

        -- b. Add Identity (Auto-Increment)
        BEGIN
            EXECUTE format('ALTER TABLE public.%I ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY', r.table_name);
            RAISE NOTICE 'Repaired Identity for table: %', r.table_name;
        EXCEPTION WHEN OTHERS THEN
            RAISE NOTICE 'Table % already has identity or sequence.', r.table_name;
        END;
    END LOOP;
END $$;

-- STEP 2: CONSTRAINT FIXES
-- ----------------------------------------------------------------
-- Ensure UNIQUE constraint on expense_categories(name)
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'expense_categories_name_key') THEN
        ALTER TABLE public.expense_categories ADD CONSTRAINT expense_categories_name_key UNIQUE (name);
    END IF;
EXCEPTION WHEN OTHERS THEN NULL;
END $$;

-- STEP 3: REBUILD AUTH TRIGGER
-- ----------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.user_profiles (user_id, email, role, status)
  VALUES (new.id, new.email, 'employee', 'pending')
  ON CONFLICT (user_id) DO NOTHING;
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- STEP 4: SYNC EXISTING USERS
-- ----------------------------------------------------------------
INSERT INTO public.user_profiles (user_id, email, role, status)
SELECT id, email, 'employee', 'pending'
FROM auth.users
ON CONFLICT (user_id) DO NOTHING;

-- STEP 5: REFRESH RLS POLICIES
-- ----------------------------------------------------------------
ALTER TABLE public.user_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cash_advances ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expense_categories ENABLE ROW LEVEL SECURITY;

-- 1. Create a non-recursive Admin Check function
CREATE OR REPLACE FUNCTION public.check_is_admin()
RETURNS BOOLEAN LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.user_profiles 
    WHERE user_id = auth.uid() 
    AND role IN ('admin', 'super_admin') 
    AND status = 'active'
  );
END;
$$;

-- 2. Helper to clear policies
CREATE OR REPLACE FUNCTION public._drop_all_policies_v4(tbl TEXT)
RETURNS VOID LANGUAGE plpgsql AS $$
DECLARE r RECORD;
BEGIN
  FOR r IN SELECT policyname FROM pg_policies WHERE tablename = tbl AND schemaname = 'public' LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', r.policyname, tbl);
  END LOOP;
END $$;

SELECT public._drop_all_policies_v4('user_profiles');
SELECT public._drop_all_policies_v4('customers');
SELECT public._drop_all_policies_v4('transactions');
SELECT public._drop_all_policies_v4('settings');
SELECT public._drop_all_policies_v4('cash_advances');
SELECT public._drop_all_policies_v4('expense_categories');

-- 3. Define Clean Policies
CREATE POLICY "up_own_all" ON public.user_profiles FOR ALL TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "up_admin_all" ON public.user_profiles FOR ALL TO authenticated USING (public.check_is_admin());

DO $$ 
BEGIN
    EXECUTE 'CREATE POLICY "customers_access" ON public.customers FOR ALL TO authenticated USING (true)';
    EXECUTE 'CREATE POLICY "transactions_access" ON public.transactions FOR ALL TO authenticated USING (true)';
    EXECUTE 'CREATE POLICY "settings_access" ON public.settings FOR ALL TO authenticated USING (true)';
    EXECUTE 'CREATE POLICY "advances_access" ON public.cash_advances FOR ALL TO authenticated USING (true)';
    EXECUTE 'CREATE POLICY "exp_cat_access" ON public.expense_categories FOR ALL TO authenticated USING (true)';
EXCEPTION WHEN OTHERS THEN NULL;
END $$;

-- STEP 6: INITIAL DATA
-- ----------------------------------------------------------------
INSERT INTO public.expense_categories (name, icon) VALUES 
('Petrol Stock', '⛽'), ('Diesel Stock', '⛽'), ('Electricity Bill', '⚡'), ('Staff Salary', '👷')
ON CONFLICT (name) DO NOTHING;

DO $$ 
BEGIN
    RAISE NOTICE 'PetroFlow Database Repair Complete!';
END $$;
